// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// InvokeHandlerFunc turns a function with the right signature into a invoke handler
type InvokeHandlerFunc func(InvokeParams) middleware.Responder

// Handle executing the request and returning a response
func (fn InvokeHandlerFunc) Handle(params InvokeParams) middleware.Responder {
	return fn(params)
}

// InvokeHandler interface for that can handle valid invoke params
type InvokeHandler interface {
	Handle(InvokeParams) middleware.Responder
}

// NewInvoke creates a new http.Handler for the invoke operation
func NewInvoke(ctx *middleware.Context, handler InvokeHandler) *Invoke {
	return &Invoke{Context: ctx, Handler: handler}
}

/* Invoke swagger:route POST /invoke service invoke

Invoke test service.

*/
type Invoke struct {
	Context *middleware.Context
	Handler InvokeHandler
}

func (o *Invoke) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewInvokeParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
