// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/combust-labs/firebox/api/models"
)

// InvokeOKCode is the HTTP code returned for type InvokeOK
const InvokeOKCode int = 200

/*InvokeOK Success

swagger:response invokeOK
*/
type InvokeOK struct {

	/*
	  In: Body
	*/
	Payload *models.HTTPResponse `json:"body,omitempty"`
}

// NewInvokeOK creates InvokeOK with default headers values
func NewInvokeOK() *InvokeOK {

	return &InvokeOK{}
}

// WithPayload adds the payload to the invoke o k response
func (o *InvokeOK) WithPayload(payload *models.HTTPResponse) *InvokeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the invoke o k response
func (o *InvokeOK) SetPayload(payload *models.HTTPResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *InvokeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// InvokeInternalServerErrorCode is the HTTP code returned for type InvokeInternalServerError
const InvokeInternalServerErrorCode int = 500

/*InvokeInternalServerError Internal Server Error

swagger:response invokeInternalServerError
*/
type InvokeInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.StandardError `json:"body,omitempty"`
}

// NewInvokeInternalServerError creates InvokeInternalServerError with default headers values
func NewInvokeInternalServerError() *InvokeInternalServerError {

	return &InvokeInternalServerError{}
}

// WithPayload adds the payload to the invoke internal server error response
func (o *InvokeInternalServerError) WithPayload(payload *models.StandardError) *InvokeInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the invoke internal server error response
func (o *InvokeInternalServerError) SetPayload(payload *models.StandardError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *InvokeInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// InvokeServiceUnavailableCode is the HTTP code returned for type InvokeServiceUnavailable
const InvokeServiceUnavailableCode int = 503

/*InvokeServiceUnavailable Service Unavailable

swagger:response invokeServiceUnavailable
*/
type InvokeServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.StandardError `json:"body,omitempty"`
}

// NewInvokeServiceUnavailable creates InvokeServiceUnavailable with default headers values
func NewInvokeServiceUnavailable() *InvokeServiceUnavailable {

	return &InvokeServiceUnavailable{}
}

// WithPayload adds the payload to the invoke service unavailable response
func (o *InvokeServiceUnavailable) WithPayload(payload *models.StandardError) *InvokeServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the invoke service unavailable response
func (o *InvokeServiceUnavailable) SetPayload(payload *models.StandardError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *InvokeServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
