// Code generated by go-swagger; DO NOT EDIT.

package vm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/combust-labs/firebox/api/models"
)

// PostVMRunOKCode is the HTTP code returned for type PostVMRunOK
const PostVMRunOKCode int = 200

/*PostVMRunOK Success

swagger:response postVmRunOK
*/
type PostVMRunOK struct {

	/*
	  In: Body
	*/
	Payload *models.VM `json:"body,omitempty"`
}

// NewPostVMRunOK creates PostVMRunOK with default headers values
func NewPostVMRunOK() *PostVMRunOK {

	return &PostVMRunOK{}
}

// WithPayload adds the payload to the post Vm run o k response
func (o *PostVMRunOK) WithPayload(payload *models.VM) *PostVMRunOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post Vm run o k response
func (o *PostVMRunOK) SetPayload(payload *models.VM) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostVMRunOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostVMRunInternalServerErrorCode is the HTTP code returned for type PostVMRunInternalServerError
const PostVMRunInternalServerErrorCode int = 500

/*PostVMRunInternalServerError Internal Server Error

swagger:response postVmRunInternalServerError
*/
type PostVMRunInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.StandardError `json:"body,omitempty"`
}

// NewPostVMRunInternalServerError creates PostVMRunInternalServerError with default headers values
func NewPostVMRunInternalServerError() *PostVMRunInternalServerError {

	return &PostVMRunInternalServerError{}
}

// WithPayload adds the payload to the post Vm run internal server error response
func (o *PostVMRunInternalServerError) WithPayload(payload *models.StandardError) *PostVMRunInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post Vm run internal server error response
func (o *PostVMRunInternalServerError) SetPayload(payload *models.StandardError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostVMRunInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
