// Code generated by go-swagger; DO NOT EDIT.

// Package server firebox
//
//  Firebox
//  Schemes:
//    http
//    https
//  Host: localhost
//  BasePath: /
//  Version: Latest
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package server
