// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HealthServiceUnavailable health service unavailable
//
// swagger:model HealthServiceUnavailable
type HealthServiceUnavailable struct {

	// Errors contains a list of errors that caused the not ready status.
	Errors map[string]string `json:"errors,omitempty"`

	// Status always contains "NOT OK".
	Status string `json:"status,omitempty"`
}

// Validate validates this health service unavailable
func (m *HealthServiceUnavailable) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this health service unavailable based on context it is used
func (m *HealthServiceUnavailable) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HealthServiceUnavailable) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HealthServiceUnavailable) UnmarshalBinary(b []byte) error {
	var res HealthServiceUnavailable
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
