// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HealthHealthy health healthy
//
// swagger:model HealthHealthy
type HealthHealthy struct {

	// details
	Details []interface{} `json:"details"`

	// Status always contains "OK".
	Status string `json:"status,omitempty"`
}

// Validate validates this health healthy
func (m *HealthHealthy) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this health healthy based on context it is used
func (m *HealthHealthy) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HealthHealthy) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HealthHealthy) UnmarshalBinary(b []byte) error {
	var res HealthHealthy
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
