// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HTTPResponse HTTP response
//
// swagger:model HTTPResponse
type HTTPResponse struct {

	// body
	Body string `json:"body,omitempty"`

	// cookies
	Cookies []string `json:"cookies,omitempty"`

	// headers
	Headers map[string]string `json:"headers"`

	// A boolean flag to indicate if the body is Base64-encoded
	IsBase64Encoded bool `json:"isBase64Encoded"`

	// multi value headers
	MultiValueHeaders map[string][]string `json:"multiValueHeaders,omitempty"`

	// status code
	StatusCode int64 `json:"statusCode,omitempty"`
}

// Validate validates this HTTP response
func (m *HTTPResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this HTTP response based on context it is used
func (m *HTTPResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HTTPResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HTTPResponse) UnmarshalBinary(b []byte) error {
	var res HTTPResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
