// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HTTPRequest HTTP request
//
// swagger:model HTTPRequest
type HTTPRequest struct {

	// body
	Body string `json:"body,omitempty"`

	// cookies
	Cookies []string `json:"cookies,omitempty"`

	// headers
	Headers map[string]string `json:"headers"`

	// http method
	HTTPMethod string `json:"httpMethod"`

	// A boolean flag to indicate if the body is Base64-encoded
	IsBase64Encoded bool `json:"isBase64Encoded"`

	// multi value headers
	MultiValueHeaders map[string][]string `json:"multiValueHeaders"`

	// encoded path hint (see EscapedPath method)
	RawPath string `json:"rawPath"`

	// encoded query values, without '?'
	RawQueryString string `json:"rawQueryString"`
}

// Validate validates this HTTP request
func (m *HTTPRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this HTTP request based on context it is used
func (m *HTTPRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HTTPRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HTTPRequest) UnmarshalBinary(b []byte) error {
	var res HTTPRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
